### ISSUE TITLE
MP still doesn't return meaningful exit codes

### ISSUE THREAD

**Issue by taltman** [Koonkie/MetaPathways_Python_Koonkie.3.0#12]
MP needs to honor the Unix convention on exit codes:

https://en.wikipedia.org/wiki/Exit_status#POSIX

It is still returning an exit code of '0' when it obviously is reporting errors in the input. All other trapped errors should be assigned distinct integer exit codes, and a human-understandable error message should be generated along with the code.

**Comment by taltman** [comment]
Can I get an update on this? This is making debugging very difficult.

**Comment by ariahahn** [comment]
95325ac64ce00ab787d3ab2275a1af543ae24ea9

**Comment by Koonkie** [comment]
done
