### ISSUE TITLE
MP should report sequence similarity tool used, and version number

### ISSUE THREAD

**Issue by taltman** [Koonkie/MetaPathways_Python_Koonkie.3.0#6]
Perhaps it already does so, but MetaPathways should create an output file after it runs that includes various parameters or third-party programs that it ended up using. For example, for running sequence similarity, it should report what tool was used (FAST vs. LAST vs. LAST+ vs. Blast+, vs. legacy Blast, etc.), and the version number.

See this issue for more context:
https://github.com/wholebiome/Fog-Dog/issues/51

**Comment by Koonkie** [comment]
reported in the run log!
