### ISSUE TITLE
MetaPathways config.txt bugs

### ISSUE THREAD

**Issue by taltman** [Koonkie/MetaPathways_Python_Koonkie.3.0#7]
Circa 2015, I am unable to get MetaPathways to work without the following lines in config.txt

PERL_EXECUTABLE 'executables/ubuntu/perl' ## Report bug 
PATHOLOGIC_EXECUTABLE '/home/altman/repos/MetaPathways_Python_Koonkie.3.0/executables/ubuntu/pathologic-placeholder'

The first one doesn't let me specify /usr/bin/perl as the path, instead, I have to put a symlink in the executables/ubuntu directory.

The second one is forcing me to specify a path to PathoLogic, even though I don't have it installed, and I am not using it as per the params.txt file. Is there a way to make this optional?

Lastly, when upgrading to MP3.0, the code was angry that I didn't have NUM_CPUS in my file. It took some sleuthing to figure this out. MP should parse the config.txt file and report helpful error messages about unexpected entries, and about expected entries that are missing. Also, the software should just default to one core if it is omitted.

**Comment by Koonkie** [comment]
MP now creates the config file on the fly!
